### ISSUE TITLE
conflict with modded doors

### ISSUE THREAD

**Issue by Reeses-Puffs** [Godlander/vpp#1]
Check issue #236 on the [bewitchment repo](https://github.com/MoriyaShiine/bewitchment) for more details (logs, screenshots).

The lowdown of it is when the shader is active, some modded doors only have textures on one side. I will post screenshots and more details soon.

**Comment by Reeses-Puffs** [comment]
![2021-12-24_14 22 13](https://user-images.githubusercontent.com/73549793/147370036-28f76de9-3dca-46e4-b2d4-d6724bbceb7a.png)
![image](https://user-images.githubusercontent.com/73549793/147370041-1cdd7cb9-354e-4045-a8c1-d2a8de44cf38.png)

**Comment by Reeses-Puffs** [comment]
[current latest.log file](https://github.com/Godlander/vpp/files/7775067/latest.log)

**Comment by Godlander** [comment]
i see the issue. should be able to fix it.
for now, you can try navigating to `assets/models/block/` and deleting everything with `door` in the name
which will remove 3D doors but also should fix the texture issues.

**Comment by Godlander** [comment]
2.4 should have fixed the issue. if it still happens let me know
