### ISSUE TITLE
1.21 Strange glowing blocks at angles & distance

### ISSUE THREAD

**Issue by willywizard** [Godlander/vpp#10]
So beyond a specific distance it seems to be making blocks glow or be uneffected by specific shaders for some reason.
I am fairly new to vanilla resource pack shaders, so I am honestly not too sure what is going on. It could possibly be my settings but I thought I would bring it up as an issue because someone told me to.

Its noticeable during the transition to night, and during night.

I am running vanilla 1.21 with the latest version of the resource pack.

![2024-07-02_21 23 38](https://github.com/Godlander/vpp/assets/7528503/c3957bb4-4d48-44ec-9c7b-34303b38a2f6)
![2024-07-02_21 20 50](https://github.com/Godlander/vpp/assets/7528503/71d3c5c9-e389-443d-a514-23962477477a)
![2024-07-02_21 21 14](https://github.com/Godlander/vpp/assets/7528503/81c557a9-6ac2-4831-a508-1cc18220a545)
![2024-07-02_21 22 27](https://github.com/Godlander/vpp/assets/7528503/7d37467d-ab6f-4f8a-9fca-3352c1b09b74)

[](https://mclo.gs/r4uA03L)

**Comment by Godlander** [comment]
can you try turning mipmap off and check?

**Comment by willywizard** [comment]
Yeah that fixed it.
I still don't know what  hat actually does tbh, but I know certain things had problems with it in the past.
