### ISSUE TITLE
Resource reload failed in vanilla 1.18.2

### ISSUE THREAD

**Issue by tezzaract** [Godlander/vpp#4]
Trying to select the pack in the latest update fails and unloads all other resource packs, with the error message "Resource reload failed" appearing as a toast. Log is attached.
![image](https://user-images.githubusercontent.com/98727110/156254796-d2a3a51e-7c1a-4e64-9a47-1fcfab376c19.png)
[latest.log](https://github.com/Godlander/vpp/files/8164964/latest.log)

**Comment by Godlander** [comment]
yes, 1.18.2 changed fog again so i'll have to fix that. i can do it later this week

**Comment by Godlander** [comment]
should be fixed. reopen if theres still issues
