### ISSUE TITLE
I want to post a modified version of the Animated Skin to be compatible with the Ears mod, what is the best way to do this?

### ISSUE THREAD

**Issue by DearFox** [Godlander/vpp#6]
I really like your resource pack\shader for blinking skins. However, the default position didn't work for me, since this place is already occupied by the Ears mod for the ears, and therefore I decided to slightly expand the possible combinations for better compatibility.
![image](https://user-images.githubusercontent.com/59219907/166454895-1239d189-f32a-464d-ba59-879818a40290.png)
My version has 4 modes for better compatibility with the Ears mod.
But it is still compatible with the original version.

**Comment by Godlander** [comment]
you can post it wherever you want, it is cc-by licensed

but v++ was not made with any mods in mind, and i think i want to keep the format simple, so i probably wont be doing that myself
